# Jekyll configuration

name: 熊昆

url: https://github.com/hustxiongkun/hustxiongkun.github.io

baseurl: '/hustxiongkun.github.io'


## default date_format
date_format: 
  title: "yyyy-mm-dd"
  archive: "mm"
  categories: "yyyy-mm"
  tag: "yyyy-mm"
# Language
lan: "cn" 

paginate: 10

highlighter: rouge
kramdown:
    input: GFM
gems: ['jekyll-paginate']

exclude: ['README.md', 'LICENSE', "*.bak"]
