# Jekyll configuration

name: 熊昆

url: https://github.com/hustxiongkun/hustxiongkun.github.io

baseurl: '/hustxiongkun.github.io'


## default date_format
date_format: 
  title: "%Y/%B/%d"
  archive: "%b"
  categories: "%b-%Y"
  tag: "%b-%Y"
# Language
lan: "cn" 

paginate: 10

highlighter: rouge
kramdown:
    input: GFM
gems: ['jekyll-paginate']

exclude: ['README.md', 'LICENSE', "*.bak"]
